# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160229_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 29, 4, 21, 46, 811048, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
