# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160315_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anon_allow',
            field=models.BooleanField(default=True),
        ),
    ]
