# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_anon_allow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='anon_allow',
            new_name='anon_allowed',
        ),
    ]
