# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_optionvotedbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvotedbyuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
