# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160323_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='total_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
