# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160406_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
