# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20160406_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
